from enum import Enum

class TruckState(Enum):
    IDLE = 0
    MOVE_TO_GATE_FOR_LOAD = 1
    WAIT_GATE_OPEN_FOR_LOAD = 2
    MOVE_TO_LOAD = 3
    WAIT_LOAD = 4
    LOADING = 5
    MOVE_TO_GATE_FOR_UNLOAD = 6
    WAIT_GATE_OPEN_FOR_UNLOAD = 7
    MOVE_TO_UNLOAD = 8
    WAIT_UNLOAD = 9
    UNLOADING = 10
    MOVE_TO_STANDBY = 11
    WAIT_NEXT_MISSION = 12
    MOVE_TO_CHARGE = 13
    CHARGING_WITH_NO_MISSION = 14
    CHARGING_WITH_MISSION = 15
    EMERGENCY_STOP = 16
