from enum import Enum

class TruckState(Enum):
    IDLE = "IDLE"
    MOVE_TO_GATE_FOR_LOAD = "MOVE_TO_GATE_FOR_LOAD"
    WAIT_GATE_OPEN_FOR_LOAD = "WAIT_GATE_OPEN_FOR_LOAD"
    MOVE_TO_LOAD = "MOVE_TO_LOAD"
    WAIT_LOAD = "WAIT_LOAD"
    LOADING = "LOADING"
    MOVE_TO_CHECKPOINT_B = "MOVE_TO_CHECKPOINT_B"
    MOVE_TO_GATE_FOR_UNLOAD = "MOVE_TO_GATE_FOR_UNLOAD"
    WAIT_GATE_OPEN_FOR_UNLOAD = "WAIT_GATE_OPEN_FOR_UNLOAD"
    MOVE_TO_UNLOAD = "MOVE_TO_UNLOAD"
    WAIT_UNLOAD = "WAIT_UNLOAD"
    UNLOADING = "UNLOADING"
    MOVE_TO_STANDBY = "MOVE_TO_STANDBY"
    WAIT_NEXT_MISSION = "WAIT_NEXT_MISSION"
    CHARGING = "CHARGING"
    EMERGENCY_STOP = "EMERGENCY_STOP"
